Some changes with map displaying
Daniel0K/FirstAngularProject pull request #14
Opened 2022-02-04 08:34 UTC by Daniel0K

Fixed positions of Booking and Adding house window.
Small refactoring.
Added button and logic for preDefinePin.

2022-02-04 14:32 UTC, YaroslavTrubanov requested changes

2022-02-04 14:32 UTC, YaroslavTrubanov commented on src/app/add-house-form/add-house-form.component.html
> +  [ngStyle]="isVisible ? { display: 'block' } : { display: 'none' }"
Почему не через ngIf?

2022-02-04 14:32 UTC, YaroslavTrubanov commented on src/app/add-house-form/add-house-form.component.ts
> +  // preDefinedPin:boolean;
Опять комментарии

2022-02-04 14:32 UTC, YaroslavTrubanov commented on src/app/pin/pin.component.html
> +  [ngClass]="
Чё за суета

2022-02-04 14:32 UTC, YaroslavTrubanov commented on src/app/pin/pin.component.ts
> +    this.changeStylePosition(this.inputPin.x, this.inputPin.y);
Опять ngOnChanges, но нужен ли он?

2022-02-07 05:28 UTC, Daniel0K commented on src/app/pin/pin.component.html
> +  [ngClass]="
претье так отформатировал, в этом вопрос?

2022-02-07 05:41 UTC, Daniel0K commented on src/app/pin/pin.component.ts
> +    this.changeStylePosition(this.inputPin.x, this.inputPin.y);
я могу subject заюзать?

2022-02-07 06:44 UTC, YaroslavTrubanov commented on src/app/pin/pin.component.html
> +  [ngClass]="
я не про форматирование, а про логику, какая то супер вложенная, явно надо в геттер уносить, если по другому никак

2022-02-07 06:44 UTC, YaroslavTrubanov commented on src/app/booking-form/booking-form.component.scss
> +  //position: absolute;
еще комментарий

2022-02-07 06:44 UTC, YaroslavTrubanov commented on src/app/pin/pin.component.ts
> +    this.changeStylePosition(this.inputPin.x, this.inputPin.y);
не, в целом ок

2022-02-07 06:56 UTC, Daniel0K commented on src/app/pin/pin.component.html
> +  [ngClass]="
у пина 3 состояния:
не активный (ключа нет)
активный (isActive)
временный-не подтвержденный ( isNotConfirmed )
в зависимости от этого должен меняться цвет, делал через классы. Не оч помимаю про геттер, где юзать и где?

2022-02-07 07:22 UTC, YaroslavTrubanov commented on src/app/pin/pin.component.html
> +  [ngClass]="
у тебя логика отображения в шаблоне, надо ее вынести в компоненту

2022-02-07 07:22 UTC, YaroslavTrubanov approved these changes

2022-02-07 07:39 UTC, merged