Added following feature: ESLint
Daniel0K/FirstAngularProject pull request #7
Opened 2022-01-22 05:57 UTC by Daniel0K

EsLint configured for ts, spec.ts and html

2022-01-23 06:06 UTC, YaroslavTrubanov requested changes

2022-01-23 06:06 UTC, YaroslavTrubanov commented on src/app/app.component.ts
> +    if (document.cookie !== '') {
Куки чаще всего не пустые, т.к. в них всегда может лежать что то, так что такая проверка тебе точно не нужна

2022-01-23 06:06 UTC, YaroslavTrubanov commented on src/app/app.component.ts
> +  hasCookie(value: string): boolean {
Такой метод надо класть в сервис для работы с куками, так как использоваться он может не только в этой компоненте
Плюс есть такой принцип как "Принцип разделения ответственности", буква S в SOLID

2022-01-23 06:06 UTC, YaroslavTrubanov commented on src/app/app.component.ts
> +        this.TestActionsService.houses.push(item);
Ты просто добавляет элементы одного массива в другой, для такого есть метод concat

2022-01-23 06:06 UTC, YaroslavTrubanov commented on src/app/app.component.ts
> +        this.TestActionsService.houses[item.id] = item;
Искать элемент лучше через метод find и не пользоваться обращением по элементу массива

2022-01-23 06:06 UTC, YaroslavTrubanov commented on src/app/pins-form/pins-form.component.ts
> +      !this.TestActionsService.checkCrossings4DatesPeriod(
Лучше переименовать метод, так как сам метод говорить "Проверить пересечение...", что подразумевает его использование как функции без возвращаемого значения, а ты используешь его в качестве проверки в конструкции if else
Например, подойдёт: "isBookingExists" если я правильно понял смысл метода. Ну вообщем направление ты понял)

2022-01-23 06:06 UTC, YaroslavTrubanov commented on src/app/services/test-actions.service.ts
> +          name.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g, '\\$1') + //eslint-disable-line
Неа, не пойдет)

2022-01-23 06:09 UTC, YaroslavTrubanov requested changes

2022-01-23 06:09 UTC, YaroslavTrubanov commented on src/app/services/test-actions.service.ts
>  export class TestActionsService {
Название сервиса странное, непонятно что делает
Также здесь работа и с куками и с бронированием, надо разделять
Почитай SOLID

2022-01-23 07:37 UTC, Daniel0K commented on src/app/app.component.ts
> +        this.TestActionsService.houses[item.id] = item;
this.TestActionsService.houses[this.TestActionsService.houses.findIndex(el => el.id === item.id)] =item;
Так чтоль?

2022-01-24 14:39 UTC, YaroslavTrubanov commented on src/app/models/pin-model.ts
> +export interface pin {
название интерфейса то все равно с большой буквы надо писать, а вот имя файла с маленькой, и model можно там не писать - просто pin.ts

2022-01-24 14:39 UTC, YaroslavTrubanov commented on src/app/models/bookings-model.ts
> +export interface bookings {
с большой надо

2022-01-24 14:45 UTC, YaroslavTrubanov commented on src/app/app.component.ts
>    checkUpdatedPinCookies() {
метод че то проверяет по название, а внутри происходят какие то присваивания

2022-01-24 14:45 UTC, YaroslavTrubanov commented on src/app/app.component.ts
> +      this.cookiesTest = <pin[]>(
че то странное название переменной

2022-01-26 09:24 UTC, YaroslavTrubanov approved these changes

2022-01-26 09:37 UTC, merged